services:
  postgres:
    image: postgres:16-alpine
    container_name: repota_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: repota_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - repota_pgdata:/var/lib/postgresql/data

volumes:
  repota_pgdata:
