import { useEffect, useState } from 'react';
import { api } from '../../api';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';

export default function Kategori() {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ name: '', description: '' }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { try { setLoading(true); setError(''); const res = await api.get('/categories'); setItems(res.data || []); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function submit(e) { e.preventDefault(); try { if (editing) await api.put(`/categories/${editing.id}`, form); else await api.post('/categories', form); setForm({ name: '', description: '' }); setEditing(null); load(); } catch (err) { alert(err.message); } }
  async function remove(id) { if (!confirm('Hapus kategori ini?')) return; try { await api.delete(`/categories/${id}`); load(); } catch (err) { alert(err.message); } }
  function edit(item) { setEditing(item); setForm({ name: item.name, description: item.description || '' }); }
  return <div className="grid xl:grid-cols-[0.8fr_1.2fr] gap-6"><form onSubmit={submit} className="card h-fit space-y-4"><div><h2 className="font-extrabold text-lg">{editing ? 'Edit Kategori' : 'Tambah Kategori'}</h2><p className="text-sm text-gray-500">Kategori penelitian Tugas Akhir SI.</p></div><div><label className="label">Nama Kategori <span className="text-red-500">*</span></label><input className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Contoh: Data Mining" /></div><div><label className="label">Deskripsi</label><textarea className="input min-h-24" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="flex gap-2 justify-end"><button type="button" className="btn-secondary" onClick={() => { setEditing(null); setForm({ name: '', description: '' }); }}>Batal</button><button className="btn-primary">{editing ? 'Simpan' : 'Tambah'}</button></div></form><section className="space-y-4">{error && <ErrorState message={error} onRetry={load} />}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState icon="category" /> : <div className="card p-0 overflow-hidden"><table className="w-full"><thead><tr><th className="table-th">Kategori</th><th className="table-th">Repository</th><th className="table-th text-right">Aksi</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="table-row"><td className="table-td"><p className="font-bold">{item.name}</p><p className="text-xs text-gray-500 mt-1">{item.description || '-'}</p></td><td className="table-td font-bold">{item.repository_count || 0}</td><td className="table-td"><div className="flex justify-end gap-2"><button className="btn-secondary py-1.5 text-xs" onClick={() => edit(item)}>Edit</button><button className="btn-danger py-1.5 text-xs" onClick={() => remove(item.id)}>Hapus</button></div></td></tr>)}</tbody></table></div>}</section></div>;
}
