import { useEffect, useState } from 'react';
import { api } from '../../api';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';

export default function Keyword() {
  const [items, setItems] = useState([]); const [categories, setCategories] = useState([]); const [form, setForm] = useState({ keyword: '', category_id: '' }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { try { setLoading(true); setError(''); const [key, cat] = await Promise.all([api.get('/keywords'), api.get('/categories')]); setItems(key.data || []); setCategories(cat.data || []); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function submit(e) { e.preventDefault(); try { if (editing) await api.put(`/keywords/${editing.id}`, form); else await api.post('/keywords', form); setForm({ keyword: '', category_id: '' }); setEditing(null); load(); } catch (err) { alert(err.message); } }
  async function remove(id) { if (!confirm('Hapus keyword ini?')) return; try { await api.delete(`/keywords/${id}`); load(); } catch (err) { alert(err.message); } }
  function edit(item) { setEditing(item); setForm({ keyword: item.keyword, category_id: item.category_id }); }
  return <div className="grid xl:grid-cols-[0.8fr_1.2fr] gap-6"><form onSubmit={submit} className="card h-fit space-y-4"><div><h2 className="font-extrabold text-lg">{editing ? 'Edit Keyword' : 'Tambah Keyword'}</h2><p className="text-sm text-gray-500">Keyword digunakan untuk kategorisasi otomatis.</p></div><div><label className="label">Keyword <span className="text-red-500">*</span></label><input className="input" value={form.keyword} onChange={(e) => setForm({ ...form, keyword: e.target.value })} placeholder="Contoh: dashboard, clustering" /></div><div><label className="label">Kategori <span className="text-red-500">*</span></label><select className="input" value={form.category_id} onChange={(e) => setForm({ ...form, category_id: e.target.value })}><option value="">Pilih kategori</option>{categories.map((cat) => <option key={cat.id} value={cat.id}>{cat.name}</option>)}</select></div><div className="flex gap-2 justify-end"><button type="button" className="btn-secondary" onClick={() => { setEditing(null); setForm({ keyword: '', category_id: '' }); }}>Batal</button><button className="btn-primary">{editing ? 'Simpan' : 'Tambah'}</button></div></form><section>{error && <ErrorState message={error} onRetry={load} />}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState icon="label" /> : <div className="card p-0 overflow-hidden"><table className="w-full"><thead><tr><th className="table-th">Keyword</th><th className="table-th">Kategori</th><th className="table-th text-right">Aksi</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="table-row"><td className="table-td font-bold">{item.keyword}</td><td className="table-td text-gray-500">{item.category_name}</td><td className="table-td"><div className="flex justify-end gap-2"><button className="btn-secondary py-1.5 text-xs" onClick={() => edit(item)}>Edit</button><button className="btn-danger py-1.5 text-xs" onClick={() => remove(item.id)}>Hapus</button></div></td></tr>)}</tbody></table></div>}</section></div>;
}
