import { useEffect, useState } from 'react';
import { api } from '../../api';
import Modal from '../../components/ui/Modal';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';
import { formatDate, truncate } from '../../utils/helpers';

export default function Verifikasi() {
  const [items, setItems] = useState([]);
  const [selected, setSelected] = useState(null);
  const [note, setNote] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  async function load() { try { setLoading(true); setError(''); const res = await api.get('/repositories/pending'); setItems(res.data || []); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function verify(id, status) { try { await api.patch(`/repositories/${id}/verify`, { status, rejection_note: note }); setSelected(null); setNote(''); load(); } catch (err) { alert(err.message); } }
  return <div className="space-y-5">{error && <ErrorState message={error} onRetry={load} />}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState icon="fact_check" title="Tidak ada pengajuan" description="Semua repository sudah diproses." /> : <div className="card overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-th">Judul</th><th className="table-th">Mahasiswa</th><th className="table-th">Kategori</th><th className="table-th">Tanggal</th><th className="table-th text-right">Aksi</th></tr></thead><tbody>{items.map((repo) => <tr className="table-row" key={repo.id}><td className="table-td font-semibold max-w-[420px]">{truncate(repo.title, 80)}</td><td className="table-td"><p className="font-semibold">{repo.submitter_name || repo.author_name}</p><p className="text-xs text-gray-400">{repo.submitter_nim || repo.submitter_email}</p></td><td className="table-td text-gray-500">{repo.category_name || '-'}</td><td className="table-td text-gray-500">{formatDate(repo.research_date || repo.created_at)}</td><td className="table-td"><div className="flex justify-end"><button onClick={() => setSelected(repo)} className="btn-primary py-1.5 text-xs"><span className="material-symbols-rounded text-[16px]">visibility</span>Detail</button></div></td></tr>)}</tbody></table></div></div>}{selected && <Modal wide title="Detail Verifikasi Repository" onClose={() => setSelected(null)}><Detail repo={selected} /><label className="label mt-5">Catatan Admin untuk Tolak/Revisi</label><textarea className="input min-h-24" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Tulis catatan jika repository ditolak atau perlu revisi" /><div className="flex flex-col sm:flex-row justify-end gap-2 mt-5"><button className="btn-secondary justify-center" onClick={() => verify(selected.id, 'revision')}><span className="material-symbols-rounded text-[18px]">edit_note</span>Revisi</button><button className="btn-danger justify-center" onClick={() => verify(selected.id, 'rejected')}><span className="material-symbols-rounded text-[18px]">cancel</span>Tolak</button><button className="btn-primary justify-center" onClick={() => verify(selected.id, 'approved')}><span className="material-symbols-rounded text-[18px]">check_circle</span>Setujui</button></div></Modal>}</div>;
}
function Detail({ repo }) { const url = repo.file_path ? api.fileUrl(repo.file_path) : null; return <div className="space-y-4"><div><p className="text-xs text-gray-500">Judul</p><h3 className="font-extrabold text-xl">{repo.title}</h3></div><div className="grid sm:grid-cols-2 gap-3"><Info label="Mahasiswa" value={repo.author_name || repo.submitter_name} /><Info label="Dosen Pembimbing" value={repo.advisor || '-'} /><Info label="Tanggal Tugas Akhir" value={formatDate(repo.research_date)} /><Info label="Kategori" value={repo.category_name || 'Otomatis setelah disetujui'} /></div><div><p className="text-xs text-gray-500">Abstrak</p><p className="text-sm text-gray-600 leading-7 mt-1 whitespace-pre-line">{repo.abstract || '-'}</p></div><div className="rounded-2xl bg-gray-50 border border-outline/40 p-4 flex items-center justify-between gap-3"><div><p className="font-bold">Dokumen PDF</p><p className="text-sm text-gray-500">{repo.file_name || 'Tidak ada file'}</p></div>{url && <a className="btn-secondary" target="_blank" rel="noreferrer" href={url}><span className="material-symbols-rounded text-[18px]">open_in_new</span>Buka Dokumen</a>}</div></div>; }
function Info({ label, value }) { return <div className="rounded-2xl bg-gray-50 border border-outline/40 p-3"><p className="text-xs text-gray-500">{label}</p><p className="font-semibold mt-1">{value}</p></div>; }
